export const IS_LOADING_ARTICLES = "IS_LOADING_API_ARTICLES";
export const SET_DAILY_ARTICLES_ERROR = "SET_DAILY_ARTICLES_ERROR"
export const SET_DAILY_ARTICLES_SUCCESS = "SET_DAILY_ARTICLES_SUCCESS";
// export const LOAD_ARTICLE_SEARCH = "LOAD_ARTICLE_SEARCH";
// export const ARTICLE_SEARCH_SUCCESS = "ARTICLE_SEARCH_SUCCESS";
// export const ARTICLE_SEARCH_ERROR = "ARTICLE_SEARCH_ERROR"

