export const IS_LOADING_ARTICLES = "IS_LOADING_API_ARTICLES";
export const FETCH_ARTICLES_SUCCEEDED = "FETCH_ARTICLES_SUCCEEDED"
export const FETCH_ARTICLES_FAILED = "FETCH_ARTICLES_FAILED";

export const SET_DAILY_ARTICLES_SUCCESS = "SET_DAILY_ARTICLES_SUCCESS"
export const SET_DAILY_ARTICLES_ERROR="SET_DAILY_ARTICLES_ERROR"