export const IS_LOADING = "IS_LOADING";
export const USER_LOGIN_SUCCEEDED = "USER_LOGIN_SUCCEEDED";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const USER_REGISTER_SUCCEEDED = "USER_REGISTER_SUCCEEDED";
export const USER_REGISTRATION_FAILED = "USER_REGISTRATION_FAILED";
export const DO_CONFIRM_REGISTRATION="DO_CONFIRM_REGISTRATION"
export const CONFIRM_REGISTRATION_SUCCEEDED = "CONFIRM_REGISTRATION_SUCCEEDED"
export const CONFIRM_REGISTRATION_FAILED = "CONFIRM_REGISTRATION_FAILED"
export const DO_LOGOUT_USER="DO_LOGOUT_USER"
export const LOGOUT_USER_FAILED= "LOGOUT_USER_FAILED"
export const LOGOUT_USER_SUCCEEDED="LOGOUT_USER_SUCCEEDED"

export const RESEND_REGISTRATIONTOKEN_SUCCEEDED ="RESEND_REGISTRATIONTOKEN_SUCCEEDED"
export const RESEND_REGISTRATIONTOKEN_FAILED ="RESEND_REGISTRATIONTOKEN_FAILED"


export const DO_ADMIN_SUCCEEDED = "GO_ADMIN_SUCCEEDE"
export const DO_ADMIN_FAILED = "GO_ADMIN_FAILED"
