export const IS_LOADING_ARTICLES = "IS_LOADING_ARTICELS";
export const GET_USER_ARTICLES_SUCCESS= 'GET_USER_ARTICLES_SUCCESS'
export const GET_USER_ARTICLES_ERROR = "GET_USER_ARTICLES_ERROR"
export const ADD_ARTICLE_TO_USER_ARTICLELIST ="ADD_ARTICLE_TO_USER_ARTICLELIST"


