export const IS_LOADING_ARTICELS = "IS_LOADING_ARTICELS";
export const GET_USER_ARTICELS_SUCCESSFUL= 'GET_USER_ARTICELS_SUCCESSFUL'
export const GET_USER_ARTICELS_ERROR = "GET_USER_ARTICELS_ERROR"

export const SET_ARTICLE_LOADING = "SET_ARTICLE_LOADING"
export const REMOVE_ARTILCLE ="REMOVE_ARTILCLE"

export const SET_BOOKMARK ="SET_BOOKMARK"
export const SET_UNBOOKMARK= "SET_UNBOOKMARK"
export const REMOVE_BOOKMARK ="REMOVE_BOOKMARK"


export const ADD_ARTICLE_TO_SAVED_ARTICLELIST ="ADD_ARTICLE_TO_SAVED_ARTICLELIST"
export const REMOVE_ARTICLE_FROM_SAVED_ARTICLELIST="REMOVE_ARTICLE_FROM_SAVED_ARTICLELIST"

export const SET_USER_ARTICLES="SET_USER_ARTICLES"

// export const SET_DAILY_ARTICLES="SET_DAILY_ARTICLES"
// export const SET_DAILY_ARTICLES_ERROR="SET_DAILY_ARTICLES_ERROR"