export const LOAD_USER_ARTICELS = "LOAD_USER_ARTICELS";
export const GET_USER_ARTICELS_SUCCESSFUL= 'GET_USER_ARTICELS_SUCCESSFUL'
export const GET_USER_ARTICELS_ERROR = "GET_USER_ARTICELS_ERROR"
// export const BOOKMARK_ARTICLE = "BOOKMARK_ARTICLE"
// export const UNBOOKMARK_ARTICLE= "UNBOOKMARK_ARTICLE"
export const SET_ARTICLE_LOADING = "SET_ARTICLE_LOADING"
export const REMOVE_ARTILCLE ="REMOVE_ARTILCLE"

export const SET_BOOKMARK ="SET_BOOKMARK"
export const SET_UNBOOKMARK= "SET_UNBOOKMARK"
export const REMOVE_BOOKMARK ="REMOVE_BOOKMARK"

export const TEST_TOGGLE ="TEST_TOGGLE"

