export const IS_LOADING_API_ARTICELS = "IS_LOADING_API_ARTICELS";
export const SET_DAILY_ARTICLES_ERROR = "SET_DAILY_ARTICLES_ERROR"
export const SET_DAILY_ARTICLES = "SET_DAILY_ARTICLES";
export const LOAD_ARTICLE_SEARCH = "LOAD_ARTICLE_SEARCH";
export const ARTICLE_SEARCH_SUCCESSFUL = "ARTICLE_SEARCH_SUCCESSFUL";
export const ARTICLE_SEARCH_ERROR = "ARTICLE_SEARCH_ERROR"

