export const LOGIN_USER_LOADING = "LOGIN_USER_LOADING";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const REGISTER_USER_LOADING = "REGISTER_USER_LOADING";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const SET_GEOLOCATION= "SET_GEOLOCATION"


export const SET_USER_TOKEN = "SET_USER_DETAILS";
export const GET_USER_INFO="GET_USER_INFO";
export const SET_USER_INFO="SET_USER_INFO";

